sudo: false
language: python
dist: xenial
matrix:
  include:
    - python: '3.7'
install:
  - pip install -r requirements.txt
  - pip install "ltd-conveyor>=0.4.2,<0.5"
script:
  - sphinx-build -b html -a -n -d _build/doctree . _build/html
after_success:
  - ltd upload --travis --dir _build/html --product ittn-011
env:
  global:
    -
      # LTD_AWS_ID
      secure: PoZdG1U/PVUiTjuVtmZZ0OsTt/BC5NvAXQ69p+ka9zQ0NLaQROXQ03rfCQ1sQOFwhbIsP43Xw30WdMzkVmzm7FfnIXTERjngTNCq/A0PY/4NAHFNnVyMvLMAFbcMxx8TpAvFUiMSPwc6e62l3uPQmhLs9U1ibQa8DpYsThv3RC54cPOaBLEWU7GlpK9fFi6/NQQHSVO7LecsfGWrtcUIoLi9s/ZQoNlxbELx3nz0ioKtUPqv6FjRvEsWTHrQlKxliOAkY2dVtOqtykQFJNoMbfLAg5psfrt9Imj23BHbcLUIuPmyAGCa1CDLHqUEs+RcS6k08zgvdLLGLo5qEqAJE9NL89jU/itJ3lRu+/cGyI6yM2tcGzz00z1k19aEkNpH88b1y9ahuxuoDOtQudy68OgqA5wEdZ29rygG0HHIUnYKaPQjCD/okVPYva+dV5r9DFwbWrPP5A6u8FVymElGYpQ+wZWe84JXw26YoW4ngrgWEcWmK8cwIJY1Hw6/qrYGjz3VyiuE0AKy/k8VVRr0AYhCZHM1Mc9feGxdKYNE6cKN+Gtdtq/xeQUry+DJcRU/oWxdPRFg5Ak9hPI0a4oX0y6GFJBzUGVMESADr+XFvOf7D/tteiKOroYh+9DYv2n6GKcCp9wC8XPXpAAJWe8JyYNzZvIfzvQ+R+YyfbD7Zwk=
    -
      # LTD_AWS_SECRET
      secure: IFyQ97H/Z4j9ShnoYwiTHwENksYPIhoH0/k7St6Bj1N+ER9APsOEfo7VWRQnuWiaAXz+0xb5Lj/qyQu+BFNXhbofDDBWoxp2r09FM1ZChIuiP4jcVWtcdbC7+ohGdYbg0xZKqY33Ko+9Ts0HqF4cNmgDhDSOv4l/S/mOx/3PJu275O5BDUx+Pc3bjA8AJNYW3+0Xm4R1pOPsa6HG2nbBTrNPpw1Ud04dckTPN5rg3fvo5t4PHMKADuEi9WEmw+fKxbRxnd8qoDMQq/Cvwg93s5hnnK74zJ9/VXiyyllpvFQKv2mZeRs52vma80NpUSItG938NX9OLvD/OCZDL5fBbD0czMgSq1H4s+0VKl4eshSfrHRrF6ffCvsidY5sShPbW9K3Ogq1ystB5VSeqULGxOpxxJ1rJNGhaHdgfO3KE7IkLe4S1X2GRPUTbZ3/U46sRRo9NGcUyvXDJvvGuH5zO38Z+w0V4HcAc/PgfwT7inZ6/s4P+L9R+3yIW9F3woDulwiUknQz/KdFHNYEmvEUtfdbpKc2YU3g9MOUWRG+9YPUFRVWroB74f/COOBqFrjHiY0W/gD7yF2dOMzFlK/YPuq/Bb48/J9BP5DX3mBO07rIA1fUTwVDtWwb4K4GFCM0tEmKbumPFulJZF/lcOSJnFuL6gQbrbQg+EO82EZP7B8=
    -
      # LTD_USERNAME
      secure: d4eU43LpTJwRyFphzcmqxS64Pax8JpanIh+iODhzVOo00IRggcAU6vFlSyLP8FyzC+dxF6fKX0uKZ/hiNJezrqBTlEJ1o1HuIN9oTlHQ6y+8YNVi4N7A4Lh7K9xYOeM9XiLBTG7I1f0grstzytEGI/OnXhL0C348AroFC4DXG+5EohPqrvwsS9j3iWRodqXQrRLEbISb7a4J1bXMsq4A3ScsBSYT4164FsMS3yRXLiLonuGIiU58CrRjwV7+hPQGOuN3VCLuNb4QWXH3TNsus9F+vpQ8zPF2cVXwVCGxMjfd+u8/xiwcE5LBZVhkTAE9GzPuU+F/KB0B+RTSCibXY4khYYjhC+ajtze+ipMjkBgk1JvkHAviH0Xgd5ix8y4IKpthlesiJoZ5A+f2sSimwB6Kcbg9atcRkvaxyhaDqoGWs1eJKOmUqpcSeFsu6tyy0AsQeix0E1756pXfZfMWbLGw5PvlKQ3gZywgEGGLjc8wSbmM8YgUPOA5JsiS/Ah6zFV8EXtpdQcTPARxQ98OY9YxnnGvdl+FGtZVPt1FXkLebSkwmxsROrPUoc9qZCGTJXkAJs6I3O+1aA9+wQ5vZz2DhBub+wLkWW/bcox2YOIV6o0ikeibth4K0MEQ2JtatroLL8V/s5+1p+wO5QT9u62KWmJKcAU6jbouJShU/dY=
    -
      # LTD_PASSWORD
      secure: z3v/Mlc/ttF9hoTjYOU9nrQ/hmQVN2ae0KG2bgWETMljnK42SjraBQmKA+ZWmQTHjZxqcdb4BhnwVvrXtPLxH23lzmgY4OSClj5lKED9gvljOfOJZjsziH+6KCwEdRpgZuqTtOyLeS6lUgcqTSuGaQnmNvCSt4mhTVcvQS8q9KfK/UbKQX7555aKFLec1eJp0IQUvMuMPFptWBNnLAQ+WHh6yjyryMm9WWEEnRWJdH2+r8RRKXCvN+GkhLkqvnkT1Y0qqIReuVEPwRUTpZu4JDwINJ0lRZSqg/1UGULjGeCzWYIwlDc8rKCwnsXpSC9AowklJrHz7tfiN6XrVsPVt5iOw/zQdh6SeQOjd0VYXODyqZuo3G0XnKlqezSThJ6505pI6OJPidKDTw8Ju5qNZDdkos/B7Fmzea6FdZUW9akU7Ph7uK7a0DoMS2PcuYYFR7gLsQ/mPMy+0M7aPdaMUlzrNMCTE9Ace6lamDb34LDcu8OORibTO50y7g8JNh0kkCbA5tJd0DKSzFI0Vsg+R0mZ5XtQMDXjtQPQRGcCzITTkLGBwlKBLoC2EpC9mHv4ft+VvMPauLPMPeiSieDCkgfu+Fc501der8xYt9EGkQaWRyhZ2laCBgVsfS3BGnkRMSRGzwfHWGjFjE4tk3XbEddzuO4iCOyOfdDqUVqN+Nk=
